version: '3'

services:
  web:
    build: ./docker/web/
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    working_dir: /app
    ports:
      - ${WEB_PORT}:80
  db:
    build: ./docker/db/
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
